## Лабораторная работа №1 | Вариант 2

Выполнил: Ефименко Кирилл Игоревич М8О-309Б-22

### 1. Numpy

In [1]:
import numpy as np

1. Создайте матрицу размером 8х8 и заполните ее шахматным рисунком

In [2]:
# chess field creation 1 - black; 0 - white
chess_field = np.zeros((8, 8), dtype=int)
chess_field[::2, ::2] = 1
chess_field[1::2, 1::2] = 1
chess_field

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

2. Каков результат выполнения следующих выражений?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```
1) NaN, так как деление на 0 не определено в математике <br>
2) 0, не выполняет никаких операций, из-за целочисленного деления, просто возвращает 0 <br>
3) [-9.22337204e+18], я предполагаю, что из-за того, что numpy написан на Си, то во время каста в int происходит черная магия и переменная заполняется "мусором" из ячейки памяти. А после, происходит обычный каст целого числа в дробное.

In [3]:
np.array(0) / np.array(0)

<ipython-input-3-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [4]:
np.array(0) // np.array(0)

<ipython-input-4-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [5]:
np.array([np.nan]).astype(int).astype(float)

<ipython-input-5-ea171f4782f5>:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

3. Создайте матрицу-шахматную доску 8х8 используя функцию `tile`

In [6]:
chess_field_template = np.tile(np.array([1, 0]), (1, 4))
chess_field_template = np.append(chess_field_template, np.tile(np.array([0, 1]), (1, 4)), axis=0)
chess_field_1 = np.tile(chess_field_template, (4, 1))
chess_field_1

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

4. Как округлить до целых массив чисел с плавающей точкой?

In [7]:
float_array = np.linspace(1, 100, 9)
print("source: ", float_array)

cast_func = np.vectorize(int)
int_array = cast_func(float_array)
print("result: ", int_array)

source:  [  1.     13.375  25.75   38.125  50.5    62.875  75.25   87.625 100.   ]
result:  [  1  13  25  38  50  62  75  87 100]


5. Как найти общие значения между двумя массивами?

In [8]:
array1 = np.array([1, 2, 3, 4, 5], dtype=int)
array2 = np.array([2, 4, 5, 7, 9], dtype=int)

intersect = np.intersect1d(array1, array2)
intersect

array([2, 4, 5])

6. Как вычислить ((A+B)*(-A/2)) на месте (без копирования)?

In [9]:
'''
В задаче не сказано, как перемножать(матрично или поэлементно),
поэтому я сделал на свой выбор. Для матричного нужно заменить
'*' на '@'
'''
A = np.ones((5, 5), dtype=int) * 12
B = np.ones((5, 5), dtype=int) * 8

res = ((A+B)*(-A/2))
res

array([[-120., -120., -120., -120., -120.],
       [-120., -120., -120., -120., -120.],
       [-120., -120., -120., -120., -120.],
       [-120., -120., -120., -120., -120.],
       [-120., -120., -120., -120., -120.]])

7. Рассмотрим случайный вектор с формой 100х2, представляющей координаты, и найдем расстояния от точки к точке

In [10]:
random_vec = np.random.rand(120, 2)

def dist(a):
  return np.sqrt(np.square(a[0]) + np.square(a[1]))

np.apply_along_axis(dist, 1, random_vec)

array([0.52496308, 0.70109336, 0.80142382, 1.09479177, 0.81217733,
       1.28339705, 0.89929022, 0.72962863, 0.93694195, 0.71353158,
       0.77802407, 1.0337754 , 0.33758563, 0.77477303, 0.36136878,
       0.93360991, 0.33543776, 0.61903042, 0.18349814, 0.5001003 ,
       0.97865181, 0.89259125, 0.91476679, 1.01753257, 0.00580495,
       0.95923559, 0.92537137, 0.64356125, 0.31062103, 0.69109701,
       0.98360097, 0.24489688, 0.1364235 , 0.42119129, 0.30173723,
       0.81105738, 0.61882466, 1.04338384, 0.83794288, 0.6527772 ,
       0.6932925 , 0.95551115, 0.58203651, 0.55676537, 0.94655786,
       0.92807527, 1.21570968, 1.23791017, 1.0044702 , 0.50191925,
       0.90227931, 0.83833256, 0.8927367 , 1.00601632, 0.30031437,
       0.77183472, 0.94199647, 0.85676142, 0.94983287, 0.8516315 ,
       0.31870897, 0.82383233, 0.96752604, 0.94098522, 0.69286436,
       0.89211669, 0.97292489, 0.64876954, 0.569723  , 0.75951191,
       0.77478919, 0.87354145, 0.88259869, 0.42887891, 0.93944

8. Как конвертировать массив float(32 bit) к массиву целых чисел (integer 32 bit) in place?

In [11]:
arr = np.linspace(1, 100, 9)
arr.astype(int)

array([  1,  13,  25,  38,  50,  62,  75,  87, 100])



9. Создайте структурированный массив, представляющий позицию (x, y) и цвет (r, g, b).

In [12]:
dtype = [('position', [('x', float), ('y', float)]), ('color', [('r', int), ('g', int), ('b', int)])]
data = np.array([((10, 10), (255, 255, 255)), ((3, 4), (0, 0, 0))], dtype=dtype)
data

array([((10., 10.), (255, 255, 255)), (( 3.,  4.), (  0,   0,   0))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<i8'), ('g', '<i8'), ('b', '<i8')])])

10. Какой эквивалент enumerate для numpy массивов?

In [13]:
# аналог - ndenumerate
a = np.array([1, 2, 3, 4])
for i, x in np.ndenumerate(a):
    print(i, x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4


### 2. Pandas

Найдите ответы на вопросы или выполните действия с предложенным датасетом

Данные о преступлениях, совершенных женщинами в Индии, с демографическими подробностями.

Файл: `CrimesOnWomenData.csv`

```
State - название штата/региона
Year - год записи
Rape - случаи изнасилования
K&A - случаи похищения
DD - смерти из-за приданого
AoW - нападение на женщин
AoM - нападение на женскую скромность(modestity)
DV - бытовое насилие
WT - торговля женщинами
```

In [14]:
import pandas as pd

In [15]:
DF_PATH = '/content/CrimesOnWomenData.csv'
df = pd.read_csv(DF_PATH)
df.head()

Unnamed: 0              State  Year  Rape   K&A   DD   AoW   AoM    DV  WT
0           0     ANDHRA PRADESH  2001   871   765  420  3544  2271  5791   7
1           1  ARUNACHAL PRADESH  2001    33    55    0    78     3    11   0
2           2              ASSAM  2001   817  1070   59   850     4  1248   0
3           3              BIHAR  2001   888   518  859   562    21  1558  83
4           4       CHHATTISGARH  2001   959   171   70  1763   161   840   0

1. За какие года представлен набор данных?

In [16]:
df['Year'].unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021])

2. Выявите район с самым высоким количеством убийств женщин

In [17]:
df.groupby('State')['DD'].sum().nlargest(1)

State
Uttar Pradesh    21357
Name: DD, dtype: int64

3. Какое среднее число изнасилований женщин в индии наблюдалось в указанные года?

In [18]:
df['Rape'].mean()

727.8559782608696

4. Выявите район с минимальным числом похищений за период 2001-2003 года

In [19]:
df[df['Year'].between(2001, 2003)].groupby('State')['K&A'].sum().nsmallest(1)

State
LAKSHADWEEP    0
Name: K&A, dtype: int64

5. Перечислите районы в которых наблюдались наиболее частые случае домашнего насилия за период с 2005 по 2012 года

In [20]:
df[df['Year'].between(2005, 2012)].groupby('State')['DV'].sum().nlargest(5)

State
WEST BENGAL       71821
ANDHRA PRADESH    62878
RAJASTHAN         50834
MAHARASHTRA       43271
UTTAR PRADESH     42215
Name: DV, dtype: int64

6. Выведите названия районов в порядке не возрастания случаев торговли женщинами за 2020 год

In [21]:
df[df['Year'] == 2020].groupby('State')['WT'].sum().sort_values(ascending=False)

State
Sikkim               231
Jharkhand            159
Madhya Pradesh        85
Punjab                67
Uttarakhand           52
Andhra Pradesh        48
Gujarat               47
Bihar                 30
Haryana               28
Tripura               25
Nagaland              19
Assam                 18
Kerala                14
Tamil Nadu            13
Odisha                11
Uttar Pradesh          8
Karnataka              5
D&N Haveli             3
Chhattisgarh           3
Jammu & Kashmir        2
Telangana              0
Rajasthan              0
Puducherry             0
A & N Islands          0
Lakshadweep            0
Mizoram                0
Meghalaya              0
Manipur                0
Maharashtra            0
Himachal Pradesh       0
Goa                    0
Delhi UT               0
Daman & Diu            0
Chandigarh             0
Arunachal Pradesh      0
West Bengal            0
Name: WT, dtype: int64

Перейдем к следующему набору данных.

Файл: `CustomerPurchasingBehaviors.csv`

Этот набор данных содержит информацию о профилях клиентов и их покупательском поведении. Данные содержат столбцы, содержащие идентификатор пользователя, возраст, годовой доход, сумму покупки, показатель лояльности (в разбивке по классам), регион и частоту покупок. Он предназначен для анализа тенденций сегментации клиентов и лояльности и может быть использован для различных задач машинного обучения и анализа данных, связанных с поведением клиентов и исследованиями рынка.

```
user_id - ID клиента
age - Возраст
annual_income - Годовой доход клиента (в долларах США).
purchase_amount - Общая сумма покупок, совершенных клиентом (в долларах США).
loyalty_score - Показатель лояльности клиента (значение от 0 до 100).
region - Регион, в котором проживает клиент (Север, Юг, Восток, Запад).
purchase_frequency - Частота покупок клиентов (количество раз в год).
```

In [22]:
DF_PATH = '/content/CustomerPurchasingBehaviors.csv'
df = pd.read_csv(DF_PATH)
df['loyalty_score'] = df['loyalty_score'].apply(lambda x: x * 10)
df.head()

user_id  age  annual_income  purchase_amount  loyalty_score region  \
0        1   25          45000              200           45.0  North   
1        2   34          55000              350           70.0  South   
2        3   45          65000              500           80.0   West   
3        4   22          30000              150           30.0   East   
4        5   29          47000              220           48.0  North   

   purchase_frequency  
0                  12  
1                  18  
2                  22  
3                  10  
4                  13

8. Какой средний годовой доход у клиентов с уровнем лояльности больше 50 живущих на севере

In [23]:
# nan == 0
print("Mean annual income: ", df[(df['loyalty_score'] > 50) & (df['region'] == 'North')]['annual_income'].mean())

Mean annual income:  60146.34146341463


9. Выведите 25 и 75 перцентили уровня лоальности клиентов живущих на западе с частотой покупок более 20 раз в год

In [24]:
df_slice = df[(df['region'] == 'West') & (df['purchase_frequency'] > 20)]['loyalty_score']
print("0.25 quantile: ", df_slice.quantile(q=0.25))
print("0.75 quantile: ", df_slice.quantile(q=0.75))

0.25 quantile:  85.0
0.75 quantile:  92.0


10. Отличается ли медианный возраст клиентов с уровнем лояльности более 70 и менее 10 для жителей Востока и Севера.

In [25]:
# nan == 0
print("The median age of North or East residents with loyalty greater than 70: ",
      df[(df['loyalty_score'] > 70) & ((df['region'] == 'North') | (df['region'] == 'East'))]['age'].median())
print("The median age of North or East residents with loyalty smaller than 10: ",
      df[(df['loyalty_score'] < 10) & ((df['region'] == 'North') | (df['region'] == 'East'))]['age'].median())

The median age of North or East residents with loyalty greater than 70:  46.0
The median age of North or East residents with loyalty smaller than 10:  nan


### 3. Визуализация

Используя библиотеки matplotlib/sns/plotly/pandas и набор данных представленный ранее визуализируйте

In [26]:
import plotly.express as px

1. Постройте диаграмму которая отражает средний уровень лояльности во всех регионах

In [27]:
DF_PATH = '/content/CustomerPurchasingBehaviors.csv'
df = pd.read_csv(DF_PATH)
df.head()

user_id  age  annual_income  purchase_amount  loyalty_score region  \
0        1   25          45000              200            4.5  North   
1        2   34          55000              350            7.0  South   
2        3   45          65000              500            8.0   West   
3        4   22          30000              150            3.0   East   
4        5   29          47000              220            4.8  North   

   purchase_frequency  
0                  12  
1                  18  
2                  22  
3                  10  
4                  13

In [28]:
fig1_data = df.groupby(by='region')['loyalty_score'].mean()
fig1 = px.bar(y=fig1_data.index.tolist(),
             x=fig1_data,
             orientation='h',
             template='simple_white',
             title='Mean loyalty by region')

fig1.update_layout(yaxis_title='Region',
                   xaxis_title='Mean loyalty score',
                  title={
                      'font': dict(size=35),
                      'x': 0.5,
                      'y': 0.9
                  })
fig1.show()

2. Постройте гистограмму распределения зарплат клиентов на Севере.

In [29]:
fig2 = px.histogram(df[df['region'] == 'North'], "annual_income",
                   template='presentation',
                   title="Distribution of clients salaries in the North",
                   nbins=10)
fig2.update_layout(title={
                      'font': dict(size=35),
                      'x': 0.5,
                      'y': 0.95
                  })
fig2.show()

3. Сравните уровни зарплат людей на севере и юге.

In [30]:
fig3_data = df[(df['region'] == 'North') | (df['region'] == 'South')].groupby(by='region')['annual_income'].mean()
fig3 = px.bar(x=fig3_data,
              y=fig3_data.index.tolist(),
              title='Mean salaries of people in the north and south',
              template='presentation',
              orientation='h'
              )
fig3.update_layout(title={
                      'font': dict(size=35),
                      'x': 0.5,
                      'y': 0.95
                   },
                   xaxis_title='annual_income',
                   yaxis_title='region'
                   )
fig3.show()

4. Постройте box plot отображающий распределение уровня лояльности для людей до 20 лет, от 20 до 40, от 40 до 60 и старше 60 лет

In [31]:
def define_category(age: int):
  if age < 20:
    return "lower 20"
  elif age >= 20 and age < 40:
    return "20 to 40"
  elif age >= 40 and age < 60:
    return "40 to 60"

  return "greater 60"

df["age_category"] = df.apply(lambda x: define_category(x['age']), axis=1)

fig4 = px.box(df, x="age_category",
              y="loyalty_score",
              title='Distribution of the loyalty score by age',
              template='presentation'
              )
fig4.update_traces(quartilemethod="exclusive")
fig4.update_layout(title={
                      'font': dict(size=30),
                      'x': 0.5,
                      'y': 0.95
                  })
fig4.show()

5. Визуализируйте зависимость частоты покупок от заработка

In [32]:
fig5 = px.scatter(df, x="annual_income",
                  y="purchase_frequency",
                  title="Dependence of the purchases frequency on annual income",
                  template='presentation')
fig4.update_layout(title={
                      'font': dict(size=30),
                      'x': 0.5,
                      'y': 0.95
                  })
fig5.show()

6. Визуализируйте как зависит сумма покупок от зарплаты клиента

In [33]:
fig5 = px.scatter(df, y="purchase_amount",
                  x="annual_income",
                  title="Dependence of the amount of purchases on the client's salary",
                  template='presentation')
fig5.update_layout(title={
                      'font': dict(size=30),
                      'x': 0.5,
                      'y': 0.95
                  })
fig5.show()

7. Придумайте как визуализировать зависимость между частотой покупок, суммой покупок и скором лояльности *

\* Задание на доп. балл

In [34]:
fig6 = px.scatter_matrix(df,
                         dimensions=['purchase_amount', 'purchase_frequency', 'loyalty_score'],
                         template='presentation')
fig6.update_layout(
    font_family="Courier New",
    title_font_family="Courier New",
    font_size=11
)
fig6.show()